//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ticket.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;&lt;head&gt;&lt;style type=&quot;text/css&quot;&gt;
        ///body{margin:0px}
        ///th{background-color:#133e5d;color:white;}
        ///table{font-size:12px;width:100%;margin:0px auto;padding:0px;border:none;border-collapse: collapse;}
        ///.head,.foot{
        /// background-color:#f1f5fe;
        /// width:100%;
        /// height:30px;
        /// line-height: 30px;
        /// text-align:center;
        ///}
        ///.foot{
        /// color:red;
        /// overflow: hidden;
        /// white-space: nowrap;
        /// font-weight: 600;position:absolute;bottom:0px;
        ///}
        ///.main{
        ///margin:0px auto;
        ///height:300px;
        ///width:750px;
        ///color:#009eff;
        ///font-size: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string default_document {
            get {
                return ResourceManager.GetString("default_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///body{margin:0px;border-top:1px solid #000;}
        ///p{
        ///margin:0px auto;
        ///font-size:12px;
        ///text-align:center;
        ///}
        ///p span{
        ///bold:bold;
        ///}select{
        ///border:0;
        ///}
        ///tbody tr{border-bottom:1px dashed #000;}
        ///th{background-color:#133e5d;color:white;}
        ///table{font-size:12px;width:100%;margin:0px auto;padding:0px;border:none;border-collapse: collapse;text-align:left;}
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;p&gt;您即将预订：{@orderInfo}&lt;p&gt;
        ///&lt;p&gt;其中：&lt;span&gt;{@seat}&lt;/span&gt;&lt;p&gt;
        ///&lt;table id=&apos;passe [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string order_document {
            get {
                return ResourceManager.GetString("order_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;&lt;head&gt;&lt;style type=&quot;text/css&quot;&gt;body{margin:0px}a:visited{color: #0000ff; text-decoration: none; }table{font-size:12px;width:100%;margin:0px auto;padding:0px;border:none;border-collapse: collapse;text-align:center;background-color:#d3d3d3;}th{background-color:#133e5d;color:white;font-size: 12px;}td{border:solid #a0a0a0 1px;font-size: 12px;}&lt;/style&gt;&lt;/head&gt;&lt;body&gt;&lt;table&gt;&lt;thead&gt;&lt;tr style=&quot;height:23px;&quot;&gt;&lt;th width=&quot;49&quot;&gt;车次&lt;/th&gt;&lt;th width=&quot;49&quot;&gt;发站&lt;/th&gt;&lt;th width=&quot;49&quot;&gt;到站&lt;/th&gt;&lt;th width=&quot;49&quot;&gt;历时&lt;/th&gt;&lt;th width=&quot;49&quot;&gt;商务座&lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string query_document {
            get {
                return ResourceManager.GetString("query_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap wifi1 {
            get {
                object obj = ResourceManager.GetObject("wifi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap wifi2 {
            get {
                object obj = ResourceManager.GetObject("wifi2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap wifi3 {
            get {
                object obj = ResourceManager.GetObject("wifi3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap wifi4 {
            get {
                object obj = ResourceManager.GetObject("wifi4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap wifi5 {
            get {
                object obj = ResourceManager.GetObject("wifi5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
